### ISSUE TITLE
undefined variable "structureOnly"

### ISSUE THREAD

**Issue by nbelyh** [jgraph/mxgraph2#27]
Here:
https://github.com/jgraph/mxgraph2/blob/bcefc1d38ca0dbff1ef1073da1e0f62cc4d4a232/javascript/src/js/view/mxGraph.js#L1953

It's actually undefined. This is the only mentioning of it. Should it be deleted maybe, or? 
It causes error when bundling.

The method is used from undo/redo.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by warmhug** [comment]
Has the new version been released?

**Comment by davidjgraph** [comment]
No, https://github.com/jgraph/mxgraph2/blob/master/ChangeLog. Use the master head for now.
