### ISSUE TITLE
Setting strokecolor and fillcolor does not work for pre-coloured shapes

### ISSUE THREAD

**Issue by lprc** [jgraph/mxgraph2#34]
Assume a stroke and/or fill color is set explicitely in the shape definition like this:

```
<shape name="TestCircle" h="46" w="46" aspect="fixed" strokewidth="inherit">
	<connections>
            <constraint x="0" y="0.5" perimeter="0" name="in"/>
            <constraint x="1" y="0.5" perimeter="0" name="out"/>
        </connections>
        <foreground>
        	<ellipse x="0" y ="0" w="46" h="46" />
        	<strokecolor color="#000000" />
        	<fillcolor color="#000000" />
            <fillstroke />
        </foreground>
</shape>
```

Then calling 

```
this.getModel().beginUpdate();
try {
	this.setCellStyles(mxConstants.STYLE_STROKECOLOR, color, cells);
	this.setCellStyles(mxConstants.STYLE_FILLCOLOR, color, cells);
} finally {
	this.getModel().endUpdate();
}
```

does not change the color. It only works if the explicit color definition in the shape definition is omitted.
I don't know if it's a bug or a feature but if the latter applies there definitely should be an option in the shape definition with which you can define if the colors may be overridden or not.

**Comment by davidjgraph** [comment]
That is the correct behaviour. If you define the colour in the declaration you're saying that's the colour. If you don't, the default is used and may be overriden on a per-cell style basis.

I'll leave it open, but I don't think we can change this without changing existing behaviour and that's a no-go.

**Comment by lprc** [comment]
Thanks for the reply! 

So as I'm building an app on top of the grapheditor example I guess I have to omit the color definition in the shape declaration and add some listeners that change the color of the inserted shape appropriately in order to keep the ability to change the color dynamically. Also I'll have to adjust the Sidebar s.t. the shape previews are displayed in the correct color. Sounds really cumbersome and thus I think the ability of setting an *initial* color in the shape declaration instead of an absolutely unalterable color would be great, maybe as a new attribute like `initial-fillcolor` so no existing behavior would be changed.

Anyways that behaviour should be described in the mxStencil doc I think.

**Comment by alderg** [comment]
If this is for a library entry, why not define the  color in the cell style?

**Comment by lprc** [comment]
What do you mean? That's what I tried initially. Is there some way of setting a default but alterable fillcolor per shape I don't know of?

**Comment by alderg** [comment]
In the sidebar, the entry typically comes with a cell style, you could define the initial colors in that cell style eg. https://github.com/jgraph/drawio-dev/blob/master/src/main/webapp/js/diagramly/sidebar/Sidebar-ER.js#L10

**Comment by lprc** [comment]
Ah I see, yeah that works, thank you!
