### ISSUE TITLE
"added" and "removed" are swapped in the "selection changed" event

### ISSUE THREAD

**Issue by nbelyh** [jgraph/mxgraph2#42]
If you get a selection change event, the "added" and "removed" items are swapped.
Means, that shapes that have been added to the selection, actually are coming "removed", and vice versa o_O
Is there a particular reason for this?

https://github.com/jgraph/mxgraph2/blob/f21069e0d0962265876aca46e0c7cda9a373d310/javascript/src/js/view/mxGraphSelectionModel.js#L434

**Comment by davidjgraph** [comment]
It's written from the perspective of the undo change.
