### ISSUE TITLE
Issue with integration with Angular

### ISSUE THREAD

**Issue by MarcoNalin** [jgraph/mxgraph2#5]
I don't know if this is a real issue to post here, in case I apologize for the inconvenience... I made a detailed post here with the issue:
https://stackoverflow.com/questions/57374610/how-to-integrate-mxgraph-with-angular-7

While integrating with Angular, it seems that the graph.insertVertex function doesn't work properly when the vertex has "relative=true". The element is not connectable in the application, even if the cell has the "connectable: true" element. I tried both the ports.html and helloport.html examples integrated with Angular and experienced the same issue.

**Comment by davidjgraph** [comment]
We have no experience with Angular or Typescript, SO is the better place to ask.
